version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: todo_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: todo_db
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todo_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - todo_network

  # PHP
  backend:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    container_name: todo_backend
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
      - ./backend/docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - mysql
    networks:
      - todo_network
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=todo_db
      - DB_USERNAME=todo_user
      - DB_PASSWORD=todo_password

  # Node.js
  frontend:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
    container_name: todo_frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - todo_network
    environment:
      - VITE_API_URL=http://localhost:8080/api

  # Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: todo_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www
      - ./backend/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - todo_network

  # PHPMyAdmin (opcjonalnie, do zarządzania bazą)
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: todo_phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root_password
    depends_on:
      - mysql
    networks:
      - todo_network

networks:
  todo_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local